spring:
  application:
    name: reactive-codechella
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/app_db
    username: ${DB_USER:docker}
    password: ${DB_PASSWORD:docker}
  flyway:
    url: jdbc:postgresql://localhost:5432/app_db
    password: ${DB_PASSWORD:docker}
    user: ${DB_USER:docker}
